name: jinou-ui
base: core20
version: '0.1'
summary: Show data from a jinou BLE sensor
description: |
  Scan and show data from Jinou sensors

grade: stable
confinement: strict
compression: lzo

apps:
  jinou-ui:
    command: usr/bin/lescan
    plugs:
      - bluez
      - bluetooth-control
      - network-observe

parts:
  hci-tools:
    source: .
    plugin: dump
    stage-packages:
      - bluez
      - bluez-hcidump
    organize:
      lescan.sh: usr/bin/lescan
